version: '3.8'

services:
  google-antigravity:
    container_name: google_antigravity
    build: .
    restart: always
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    networks:
      - orchestrator_factory_net

networks:
  orchestrator_factory_net:
    external: true
